-- Run once before using the availability CRUD endpoints.
-- The supplied table definition needs a generated id for POST requests.
CREATE TABLE IF NOT EXISTS tutor_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_user_id VARCHAR(50) NOT NULL REFERENCES tutor_profiles(user_id),
    slot_date DATE NOT NULL,
    day_name VARCHAR(20) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME,
    status VARCHAR(20) NOT NULL
);

-- For databases where the table was already created with `id BIGINT PRIMARY KEY`.
CREATE SEQUENCE IF NOT EXISTS tutor_availability_id_seq;
ALTER TABLE tutor_availability
  ALTER COLUMN id SET DEFAULT nextval('tutor_availability_id_seq');
SELECT setval(
  'tutor_availability_id_seq',
  COALESCE((SELECT MAX(id) FROM tutor_availability), 0) + 1,
  false
);
